receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
        cors:
          allowed_origins:
            - http://*
            - https://*

processors:
  transform:
    log_statements:
      - set(log.attributes, { "service.name": log.attributes["service.name"], "service.namespace": log.attributes["service.namespace"] })
      - set(log.attributes, { "url": log.body["url"], "message": log.body["message"], "kind_of": log.body["kind_of"] })
      # - from: log.body
      #   to: log.attributes.url
      #   actions:
      #     - type: set
      #       expression: json.parse(log.body).url
      # - from: log.body
      #   to: log.attributes.message
      #   actions:
      #     - type: set
      #       expression: json.parse(log.body).message
      # - from: log.body
      #   to: log.attributes.kind_of
      #   actions:
      #     - type: set
      #       expression: json.parse(log.body).kind_of
      # - from: resource.attributes["service.name"]
      #   to: log.attributes.module
      #   actions:
      #     - type: set
      #       expression: resource.attributes["service.name"]
  batch:
    timeout: 1s
    send_batch_size: 10000
  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
    spike_limit_mib: 200

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
    
exporters:
  # otlphttp/openobserve:
  #   endpoint: http://localhost:5080/api/default
  #   headers:
  #     Authorization: Basic YWRtaW5AYWRtaW4uY29tOmZ4VHl0MGFzbDBGbHVMRGk=
  #     stream-name: default
  
  # otlp/openobserve:
  #   endpoint: openobserve:5081
  #   headers:
  #     Authorization: "Basic YWRtaW5AYWRtaW4uY29tOmZ4VHl0MGFzbDBGbHVMRGk="
  #     organization: default
  #     stream-name: default
  #   tls:
  #     insecure: true
  
  clickhouse:
    endpoint: tcp://clickhouse:9000?dial_timeout=10s&compress=lz4
    # ttl: 96h
    database: logs_db
    username: admin
    password: admin123
    timeout: 10s
    create_schema: false #Turn off the automatic schema feature, defualt is true create table: otel_logs, otel_traces
    async_insert: true
    logs_table_name: log
    sending_queue:
      queue_size: 100
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

  debug:
    verbosity: detailed

service:
  extensions: [health_check]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      # exporters: [otlp/openobserve]
      exporters: [clickhouse]
    traces:
      receivers: [otlp]
      processors: [batch]
      # exporters: [clickhouse]
      exporters: [debug]

  telemetry:
    logs:
      level: debug