receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
        cors:
          allowed_origins:
            - http://*
            - https://*

processors:
  transform:
    log_statements:
      - context: log
        statements:
          - set(attributes["module"], resource.attributes["service.name"])
          # - set(attributes["url"], json.parse(log_record.body["url"]))
          - set(attributes, ParseJSON(body))
          # - set(attributes["timestamp"], time_unix_nano)
          # - set(timestamp, time_unix_nano)
          # - set(attributes["severity"], SeverityText)
          - delete_key(attributes, "Trace ID")
          - delete_key(attributes, "SeverityText")
          - delete_key(attributes, "Body")
  resource:
    attributes:
      - key: Trace ID
        from_attribute: Trace ID
        action: upsert

  batch:
    timeout: 1s
    send_batch_size: 10000
  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
    spike_limit_mib: 200

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
    
exporters:
  # otlphttp/openobserve:
  #   endpoint: http://localhost:5080/api/default
  #   headers:
  #     Authorization: Basic YWRtaW5AYWRtaW4uY29tOmZ4VHl0MGFzbDBGbHVMRGk=
  #     stream-name: default
  
  # otlp/openobserve:
  #   endpoint: openobserve:5081
  #   headers:
  #     Authorization: "Basic YWRtaW5AYWRtaW4uY29tOmZ4VHl0MGFzbDBGbHVMRGk="
  #     organization: default
  #     stream-name: default
  #   tls:
  #     insecure: true
  
  clickhouse:
    endpoint: tcp://clickhouse:9000?dial_timeout=10s&compress=lz4
    # ttl: 96h
    database: logs_db
    username: admin
    password: admin123
    timeout: 10s
    ##Turn off the automatic schema feature, defualt is true create table: otel_logs, otel_traces
    create_schema: true
    async_insert: true
    # logs_table_name: log
    # logs_table_name: "log"
    sending_queue:
      queue_size: 100
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

  debug:
    verbosity: detailed

service:
  extensions: [health_check]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [transform, batch, resource]
      # exporters: [otlp/openobserve]
      exporters: [clickhouse, debug]
    # traces:
    #   receivers: [otlp]
    #   processors: [batch]
    #   # exporters: [clickhouse]
    #   exporters: [debug]

  telemetry:
    logs:
      level: debug