# version: '3.8'

services:
  fastapi:
    container_name: app
    build:
      context: ./service
    ports:
      - "5002:5002"
    environment:
      - OTEL_RESOURCE_ATTRIBUTES='service.name=demo_app'
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_ENDPOINT='collector:4317'
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
      - GRPC_VERBOSITY=debug
      - GRPC_TRACE=http,call_error,connectivity_state
      # - OTEL_EXPORTER_OTLP_PROTOCOL='grpc'
    volumes:
      - ./service/app:/app
    restart: always
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5002", "--reload"]
    networks:
      - observability

  # openobserve:
  #   image: public.ecr.aws/zinclabs/openobserve:latest
  #   container_name: openobserve
  #   restart: unless-stopped
  #   environment:
  #     ZO_ROOT_USER_EMAIL: "admin@admin.com"
  #     ZO_ROOT_USER_PASSWORD: "admin@1234"
  #   ports:
  #   - "5080:5080"
  #   - "5081:5081"
  #   volumes:
  #     - ./observe:/data
  #   networks:
  #     - observability
  #   # depends_on:
  #   #   - collector

  collector:
    build:
      context: ./collector-gateway
    container_name: collector
    volumes:
      - ./collector-gateway/config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
    #- 1888:1888 # pprof extension
    #- 8888:8888 # Prometheus metrics exposed by the Collector
    # - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
    # environment:
    #   - OTEL_EXPORTERS_OTLP_TLS_INSECURE=true
    # command: ["--config=/etc/otelcol-contrib/config.yaml", "--set=extensions.health_check.endpoint=:13133"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:13133"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - observability
    # depends_on:
    #   - openobserve

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: always
    ports:
      - "8123:8123"  # HTTP Interface (API)
      - "9000:9000"  # Native Interface (Client)
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
      # - ./clickhouse-config.xml:/etc/clickhouse-server/config.xml
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin123
      CLICKHOUSE_DB: logs_db
    networks:
      - observability

networks:
  observability:
    driver: bridge